Repository svalinn/parastell, pull requests merged in 2025-04, with the labels that each got.

#208 Fix bug where zero volume coils make the material tag list too long in CAD-to-DAGMC workflow
  parastell/magnet_coils.py
  parastell/parastell.py
  tests/files_for_tests/circular_coils.example
  tests/test_magnet_coils.py
Labels: bug

#204 Fix error for edge case when computing magnet coil outboard mid-plane index
  parastell/magnet_coils.py
  tests/test_magnet_coils.py
Labels: bug

#209 Update NWL utility
  .gitignore
  Examples/nwl_example.py
  Examples/nwl_geom_example.py
  Examples/nwl_plot_example.py
  parastell/nwl_utils.py
  tests/files_for_tests/cross_sections/01H_001.h5
  tests/files_for_tests/cross_sections/01H_002.h5
  tests/files_for_tests/cross_sections/01H_003.h5
  tests/files_for_tests/cross_sections/cross_sections.xml
  tests/files_for_tests/nwl_geom.h5m
  tests/files_for_tests/source_mesh.h5m
  tests/files_for_tests/strengths.npy
  tests/test_nwl.py
Labels: documentation, enhancement, testing, nwl

#210 Add open-source volumetric meshing routines
  Examples/custom_first_wall_profile_example.py
  Examples/custom_source_example.py
  Examples/parastell_cad_to_dagmc_example.py
  Examples/parastell_cubit_example.py
  Examples/parastell_pydagmc_example.py
  Examples/radial_distance_example.py
  parastell/cubit_utils.py
  parastell/invessel_build.py
  parastell/magnet_coils.py
  parastell/parastell.py
  parastell/source_mesh.py
  parastell/utils.py
  tests/test_invessel_build.py
  tests/test_magnet_coils.py
  tests/test_parastell.py
  tests/test_source_mesh.py
Labels: enhancement, magnets, blankets, meshing_feature
